sudo: required
services:
    - docker
before_install:
    - docker build -t node/docker-react -f Dockerfile.dev .
script:
    - docker run node/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-504533686223"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"

